### ISSUE TITLE
Escape text fields

### ISSUE THREAD

**Issue by SergeC** [Webonaute/DoctrineFixturesGeneratorBundle#10]
Some of my fields contain HTML and they are exported incorrectly when double quotes is in text. I've added `htmlentities` at line 263 `$setValue = '"' . htmlentities($value) . '"';` to `\Webonaute\DoctrineFixturesGeneratorBundle\Tool\FixtureGenerator::generateFixtureItemStub`

**Comment by SergeC** [comment]
This should be better:
`                    $setValue = "<<<EOT
$value
EOT".PHP_EOL;`

**Comment by Webonaute** [comment]
Please provide a patch and I will include it with pleasure.

**Comment by remedge** [comment]
I faced with the same issue. Can I make a patch?

**Comment by SergeC** [comment]
@remedge Sure. Best way to do it with `<<<`.

**Comment by remedge** [comment]
@Webonaute please check the PR https://github.com/Webonaute/DoctrineFixturesGeneratorBundle/pull/18

**Comment by Webonaute** [comment]
anyone can confirm the patch is working or create a unit test for it? I am little busy actually and dont have time to test it until this weekend.

**Comment by Webonaute** [comment]
Please provide also an example of text that was not working and now working with the patch.

**Comment by remedge** [comment]
For example, text containig double quotes -  `'<a href="http://github.com/">bla bla bla</a>'`

I can provide unit test but little later.

**Comment by Webonaute** [comment]
@remedge thank. I appreciate!

**Comment by SergeC** [comment]
Not tested but looks good.

**Comment by Webonaute** [comment]
@SergeC Sorry but I can't include a patch on a "it's look good" because it look good to mee too! but I dont want to include patch without at least 2 developer asserting its working after test or the patch author provide a proper unit test or I have personally tested it.

**Comment by SergeC** [comment]
@Webonaute @remedge Tested, worked for me.

**Comment by Webonaute** [comment]
Added to master.
