### ISSUE TITLE
error in installation

### ISSUE THREAD

**Issue by Soolan** [Webonaute/DoctrineFixturesGeneratorBundle#12]
Hi,
Thank you for your bundle. When I try to install it via this command:
composer require Webonaute\DoctrineFixturesGeneratorBundle 'dev-master'

I got following error:
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - The requested package webonautedoctrinefixturesgeneratorbundle could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

Can you help me with that please?
Thank you.

**Comment by Webonaute** [comment]
Please Check other ticket, it has been asked already!

Le mardi 15 septembre 2015, Sohail Salehi <notifications@github.com> a
écrit :

> Hi,
> Thank you for your bundle. When I try to install it via this command:
> composer require Webonaute\DoctrineFixturesGeneratorBundle 'dev-master'
>
> I got following error:
> Your requirements could not be resolved to an installable set of packages.
> Problem 1
> - The requested package webonautedoctrinefixturesgeneratorbundle could not
> be found in any version, there may be a typo in the package name.
>
> Potential causes:
>
>    - A typo in the package name
>    - The package is not available in a stable-enough version according to
>    your minimum-stability setting see
>    https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion
>    for more details.
>
> Read https://getcomposer.org/doc/articles/troubleshooting.md for further
> common problems.
>
> Installation failed, reverting ./composer.json to its original content.
>
> Can you help me with that please?
> Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Webonaute/DoctrineFixturesGeneratorBundle/issues/12>.
>


-- 
Mathieu Delisle
Analyste-Programmeur Sénior
514.465.6335

P.S. Le présent courriel et toutes les pièces jointes contiennent de
l'information privée, exclusive, privilégiée et/ou confidentielle, sujette
au droit d'auteur, s'adressant uniquement au destinataire. Toute
utilisation, copie ou distribution non autorisée du contenu de ce courriel
est strictement interdite. Si vous n'êtes pas le destinataire de ce message
et que vous l'avez reçu par erreur, veuillez le supprimer et en informer
immédiatement l'expéditeur.

**Comment by Soolan** [comment]
can you provide a link to that ticket please?

**Comment by Webonaute** [comment]
Its just the latest ticket before yours x.X

https://github.com/Webonaute/DoctrineFixturesGeneratorBundle/issues/11
