### ISSUE TITLE
Doctrine2 Array fields and underscores in properties

### ISSUE THREAD

**Issue by niou-ns** [Webonaute/DoctrineFixturesGeneratorBundle#2]
Hi!
Great work you've done here, but there is a few problems, with I've fixed in version witch is forked in my profile. I've done this fix because it was really important in my project.

For example - my property was $only_once, but setter and getter looked like setOnlyOnce - your code didn't work.
There was a problem with boolean - the "false" value didn't appear as 0 - it was throwing an exception during loading fixture.
And the very important change - array field for doctrine entity.

**Comment by Webonaute** [comment]
I merged your change to the master. Thank you.
