### ISSUE TITLE
 Table 'sfk.wbnt_dfgb_test' doesn't exist

### ISSUE THREAD

**Issue by vikramparihar** [Webonaute/DoctrineFixturesGeneratorBundle#21]
Hi when i m loading fixture after generating then getting error in console 
" Base table or view not found: 1146 Table 'sfk.wbnt_dfgb_test' doesn't exist" 
How to pass table name is fixtures

**Comment by Webonaute** [comment]
please provide code example so I can reproduce the issue.

**Comment by jmaheux** [comment]
I had the same error. Turned out it was caused by having `auto_mapping: true` in entity manager config. I just changed it to manually set name of bundles [as explained here](http://symfony.com/doc/current/cookbook/doctrine/multiple_entity_managers.html).

**Comment by Webonaute** [comment]
thank @jmaheux.
