### ISSUE TITLE
Error while loading fixture

### ISSUE THREAD

**Issue by jpyzio** [Webonaute/DoctrineFixturesGeneratorBundle#23]
When I try load fixture I receive this error:
`php app/console doctrine:fixtures:load`
`[Symfony\Component\Debug\Exception\ContextErrorException]`
`Notice: Undefined variable: IkNrAcolIrBKqAzpvhKCSeUnR7uESLsSH`

Description:
All values in fixture are in quotation marks, but when I trying to load them like below, hash string is interpreted as variable.
`$item2->setPassword("$2y$13$IkNrAcolIrBKqAzpvhKCSeUnR7uESLsSH/kHIte8mzAuwshKeF48a");`

Solution:
Change the quote on the apostrophe like below or escape all special characters:
`$item2->setPassword('$2y$13$IkNrAcolIrBKqAzpvhKCSeUnR7uESLsSH/kHIte8mzAuwshKeF48a');`

**Comment by Webonaute** [comment]
added escaping for $ sign in v1.3.0
