### ISSUE TITLE
Generate fixtures with "UUID" GeneratedValue strategy for id

### ISSUE THREAD

**Issue by glevolod** [Webonaute/DoctrineFixturesGeneratorBundle#25]
Names of fixtures' variables are generated automatically. As I see it is concatenation of string "$item" and value of "id" column of record. If your use "UUID" GeneratedValue strategy for "id" property of your entity, then your will have a variable with name like "$item810f5dd4-a4f5-11e6-b400-84a6c8a557e4" with non permitted symbols "-".
I propose to replace "-" with "_" before writing fixtures' files.

**Comment by Webonaute** [comment]
I will include it into the experimental branch I am working on.

**Comment by glevolod** [comment]
I just have done a #26 merge request with this improvement.

**Comment by Webonaute** [comment]
I added the code into the Experimental branch.

**Comment by Webonaute** [comment]
tagged as version 1.3.

**Comment by glevolod** [comment]
Thanks, I'll try it!
