### ISSUE TITLE
The namespace is wrong

### ISSUE THREAD

**Issue by jmaheux** [Webonaute/DoctrineFixturesGeneratorBundle#31]
I'm not sure how people are able to get this bundle working without modifying the namespace in every generated file but I guess their setup is different from mine. I was always getting Class not found errors until I realized that. I looked but I didn't see any configuration for the data fixtures directory. The folder where the fixtures are generated is plural:

https://github.com/Webonaute/DoctrineFixturesGeneratorBundle/blob/master/Generator/DoctrineFixtureGenerator.php#L75

While the generated namespace is singular:

https://github.com/Webonaute/DoctrineFixturesGeneratorBundle/blob/master/Tool/FixtureGenerator.php#L481

This forces me to change the namespace in every generated file so I can actually load the fixtures. Am I missing something?

**Comment by Webonaute** [comment]
Do you use DoctrineFixturesBundle? http://symfony.com/doc/current/bundles/DoctrineFixturesBundle/index.html
The Fixture Generator generate code for this bundle.

It work perfectly on many of my projects.

**Comment by Webonaute** [comment]
Oh you are right. there is a bug. I think the composer fix the issue by doing the optimized autoload dump. I will fix it

**Comment by Webonaute** [comment]
Please try version 1.3.5 or latest Master.

**Comment by jmaheux** [comment]
Thanks for fixing it. Unfortunately, I can't install 1.3.5 since it requires PHP >= 7.0 and we're still on PHP 5.5. 

At least I know how to make it work and it's not a big change to do. Thanks for this useful bundle.
