### ISSUE TITLE
getDialogHelper method not available

### ISSUE THREAD

**Issue by jroenf** [Webonaute/DoctrineFixturesGeneratorBundle#5]
on "php bin/console Doctrine:Generate:Fixture --entity=Blog:BlogPost --ids="12 534 124" --name="bug43""

Attempted to call method "getDialogHelper" on class "Webonaute\DoctrineFixturesGeneratorBundle\Command\GenerateDoctrineFixtureCommand".

**Comment by Webonaute** [comment]
I removed the support for symfony 2.5 for the current version. a fix is coming for the 2.5 later today.

**Comment by Webonaute** [comment]
version 1.1.2 now support symfony 2.5.
