### ISSUE TITLE
Command "doctrine:generate:fixture" is not defined.

### ISSUE THREAD

**Issue by maykino** [Webonaute/DoctrineFixturesGeneratorBundle#55]
console.ERROR: Error thrown while running command "'doctrine:generate:fixture'". Message: "Command "doctrine:generate:fixture" is not defined.

On symfony 4.1

**Comment by samail** [comment]
Hi, 
Same here with SF4.2.1

**Comment by ilicmsreten** [comment]
Same for SF2.8.49

**Comment by alkinoy** [comment]
Same in SF4.2

Bundle added in config/bundles.php, appeared in composer.json and composer.lock, vendor code exists in vendor folder, but command is absent in available list...
