### ISSUE TITLE
Exclude columns from fixture

### ISSUE THREAD

**Issue by acpbytron** [Webonaute/DoctrineFixturesGeneratorBundle#9]
Possible enhancement ...
  add a command line option to ignore columns/member variables from the entity if there are columns that need to be left null in the new fixture.

**Comment by Webonaute** [comment]
Nice idea, maybe for later, 

by the way, since v1.3.0, the fixture generator will not add line for columns that are equal to the default value in entity. It will reduce significantly the number of line of code some big table.

**Comment by Webonaute** [comment]
You can ignore already column data using Annotation. look at the documentation.
